language: node_js

node_js:
  - 12

cache:
  directories:
    - node_modules

before_install:
  - npm install -g yarn

before_script:
  - yarn install

script:
  - yarn build && yarn lint && yarn test

email:
  - bum@avarteq.de
